### ISSUE TITLE
Version Jetpack

### ISSUE THREAD

**Issue by romain87400** [patterson163/TensorRT-PeopleNet#1]
Hello @patterson163 

I'm trying your code but i'm cannot used or converted models. 
If i try directly command ./main.py, an error come with this message "[TensorRT] ERROR: coreReadArchive.cpp (38) - Serialization Error in verifyHeader: 0 (Version tag does not match)

And if i'm try to convert model resnet34_peoplenet_pruned.etlt with tlt-converter 7.1, i'm this error : 
[ERROR] UffParser: Unsupported number of graph 0

I think problem from of my os version or other older librairies.
Can you share your configuration that you used with your program ? 
Thanks for your help, best regards.
Romain Mamont

**Comment by patterson163** [comment]
@romain87400 Thanks for using the code.My version of jetpack is V4.3 or V4.4 or V4.4.1.I converted the model on the jetson Nano 4GB.You can try it.

**Comment by patterson163** [comment]
Already answered the question.
